//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazDATMA.TutorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.datmasoft.datma.pe/", ConfigurationName="TutorWS.TutorWS")]
    public interface TutorWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/listarTutoresPorNombreRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/listarTutoresPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.TutorWS.listarTutoresPorNombreResponse listarTutoresPorNombre(InterfazDATMA.TutorWS.listarTutoresPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/listarTutoresPorNombreRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/listarTutoresPorNombreResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.listarTutoresPorNombreResponse> listarTutoresPorNombreAsync(InterfazDATMA.TutorWS.listarTutoresPorNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/listarTodosTutoresRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/listarTodosTutoresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.TutorWS.listarTodosTutoresResponse listarTodosTutores(InterfazDATMA.TutorWS.listarTodosTutoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/listarTodosTutoresRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/listarTodosTutoresResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.listarTodosTutoresResponse> listarTodosTutoresAsync(InterfazDATMA.TutorWS.listarTodosTutoresRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/verificarDNIRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/verificarDNIResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.TutorWS.verificarDNIResponse verificarDNI(InterfazDATMA.TutorWS.verificarDNIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/verificarDNIRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/verificarDNIResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.verificarDNIResponse> verificarDNIAsync(InterfazDATMA.TutorWS.verificarDNIRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/insertarTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/insertarTutorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.TutorWS.insertarTutorResponse insertarTutor(InterfazDATMA.TutorWS.insertarTutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/insertarTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/insertarTutorResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.insertarTutorResponse> insertarTutorAsync(InterfazDATMA.TutorWS.insertarTutorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/modificarTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/modificarTutorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.TutorWS.modificarTutorResponse modificarTutor(InterfazDATMA.TutorWS.modificarTutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/modificarTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/modificarTutorResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.modificarTutorResponse> modificarTutorAsync(InterfazDATMA.TutorWS.modificarTutorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/eliminarTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/eliminarTutorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.TutorWS.eliminarTutorResponse eliminarTutor(InterfazDATMA.TutorWS.eliminarTutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TutorWS/eliminarTutorRequest", ReplyAction="http://services.datmasoft.datma.pe/TutorWS/eliminarTutorResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.eliminarTutorResponse> eliminarTutorAsync(InterfazDATMA.TutorWS.eliminarTutorRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class tutor : usuario {
        
        private int activoTutorField;
        
        private int bajoRecursosField;
        
        private int diaField;
        
        private int dispositivosField;
        
        private int gestanteField;
        
        private grupo[] gruposField;
        
        private int redesSocialesField;
        
        private int tiposConexionField;
        
        private int turnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activoTutor {
            get {
                return this.activoTutorField;
            }
            set {
                this.activoTutorField = value;
                this.RaisePropertyChanged("activoTutor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int bajoRecursos {
            get {
                return this.bajoRecursosField;
            }
            set {
                this.bajoRecursosField = value;
                this.RaisePropertyChanged("bajoRecursos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int dispositivos {
            get {
                return this.dispositivosField;
            }
            set {
                this.dispositivosField = value;
                this.RaisePropertyChanged("dispositivos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int gestante {
            get {
                return this.gestanteField;
            }
            set {
                this.gestanteField = value;
                this.RaisePropertyChanged("gestante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("grupos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public grupo[] grupos {
            get {
                return this.gruposField;
            }
            set {
                this.gruposField = value;
                this.RaisePropertyChanged("grupos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int redesSociales {
            get {
                return this.redesSocialesField;
            }
            set {
                this.redesSocialesField = value;
                this.RaisePropertyChanged("redesSociales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int tiposConexion {
            get {
                return this.tiposConexionField;
            }
            set {
                this.tiposConexionField = value;
                this.RaisePropertyChanged("tiposConexion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
                this.RaisePropertyChanged("turno");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class grupo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantInfantesField;
        
        private tutor[] cuidadoresField;
        
        private curso cursoField;
        
        private int idGrupoField;
        
        private int maxCantCuidadoresField;
        
        private string nombrePromocionField;
        
        private psicologo[] psicologosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantInfantes {
            get {
                return this.cantInfantesField;
            }
            set {
                this.cantInfantesField = value;
                this.RaisePropertyChanged("cantInfantes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cuidadores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public tutor[] cuidadores {
            get {
                return this.cuidadoresField;
            }
            set {
                this.cuidadoresField = value;
                this.RaisePropertyChanged("cuidadores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public curso curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
                this.RaisePropertyChanged("curso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idGrupo {
            get {
                return this.idGrupoField;
            }
            set {
                this.idGrupoField = value;
                this.RaisePropertyChanged("idGrupo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int maxCantCuidadores {
            get {
                return this.maxCantCuidadoresField;
            }
            set {
                this.maxCantCuidadoresField = value;
                this.RaisePropertyChanged("maxCantCuidadores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombrePromocion {
            get {
                return this.nombrePromocionField;
            }
            set {
                this.nombrePromocionField = value;
                this.RaisePropertyChanged("nombrePromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("psicologos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public psicologo[] psicologos {
            get {
                return this.psicologosField;
            }
            set {
                this.psicologosField = value;
                this.RaisePropertyChanged("psicologos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class curso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantSemanasField;
        
        private string descripcionField;
        
        private int estadoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private System.DateTime fechaInscripcionField;
        
        private bool fechaInscripcionFieldSpecified;
        
        private grupo[] gruposField;
        
        private int idCursoField;
        
        private requerimiento[] requerimientosField;
        
        private semana[] semanasField;
        
        private tema[] temasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantSemanas {
            get {
                return this.cantSemanasField;
            }
            set {
                this.cantSemanasField = value;
                this.RaisePropertyChanged("cantSemanas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaInscripcion {
            get {
                return this.fechaInscripcionField;
            }
            set {
                this.fechaInscripcionField = value;
                this.RaisePropertyChanged("fechaInscripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInscripcionSpecified {
            get {
                return this.fechaInscripcionFieldSpecified;
            }
            set {
                this.fechaInscripcionFieldSpecified = value;
                this.RaisePropertyChanged("fechaInscripcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("grupos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public grupo[] grupos {
            get {
                return this.gruposField;
            }
            set {
                this.gruposField = value;
                this.RaisePropertyChanged("grupos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requerimientos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public requerimiento[] requerimientos {
            get {
                return this.requerimientosField;
            }
            set {
                this.requerimientosField = value;
                this.RaisePropertyChanged("requerimientos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("semanas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public semana[] semanas {
            get {
                return this.semanasField;
            }
            set {
                this.semanasField = value;
                this.RaisePropertyChanged("semanas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("temas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public tema[] temas {
            get {
                return this.temasField;
            }
            set {
                this.temasField = value;
                this.RaisePropertyChanged("temas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class requerimiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idCursoReqField;
        
        private int idRequerimientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCursoReq {
            get {
                return this.idCursoReqField;
            }
            set {
                this.idCursoReqField = value;
                this.RaisePropertyChanged("idCursoReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idRequerimiento {
            get {
                return this.idRequerimientoField;
            }
            set {
                this.idRequerimientoField = value;
                this.RaisePropertyChanged("idRequerimiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class tema : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class semana : object, System.ComponentModel.INotifyPropertyChanged {
        
        private curso cursoField;
        
        private string descripcionField;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public curso curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
                this.RaisePropertyChanged("curso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class distrito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idDistritoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idDistrito {
            get {
                return this.idDistritoField;
            }
            set {
                this.idDistritoField = value;
                this.RaisePropertyChanged("idDistrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(psicologo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tutor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string celularField;
        
        private string correoField;
        
        private string dNIField;
        
        private distrito distritoField;
        
        private int edadField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private ushort generoField;
        
        private int idPersonaField;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
                this.RaisePropertyChanged("DNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public distrito distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(psicologo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tutor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class usuario : persona {
        
        private int activoField;
        
        private byte[] fotoPerfilField;
        
        private int idUsuarioField;
        
        private string passwordField;
        
        private int tipoField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fotoPerfil {
            get {
                return this.fotoPerfilField;
            }
            set {
                this.fotoPerfilField = value;
                this.RaisePropertyChanged("fotoPerfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class psicologo : usuario {
        
        private int activoPsicologoField;
        
        private curso[] cursosField;
        
        private grupo[] gruposField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activoPsicologo {
            get {
                return this.activoPsicologoField;
            }
            set {
                this.activoPsicologoField = value;
                this.RaisePropertyChanged("activoPsicologo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cursos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public curso[] cursos {
            get {
                return this.cursosField;
            }
            set {
                this.cursosField = value;
                this.RaisePropertyChanged("cursos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("grupos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public grupo[] grupos {
            get {
                return this.gruposField;
            }
            set {
                this.gruposField = value;
                this.RaisePropertyChanged("grupos");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTutoresPorNombre", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarTutoresPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreTutor;
        
        public listarTutoresPorNombreRequest() {
        }
        
        public listarTutoresPorNombreRequest(string nombreTutor) {
            this.nombreTutor = nombreTutor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTutoresPorNombreResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarTutoresPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.TutorWS.tutor[] @return;
        
        public listarTutoresPorNombreResponse() {
        }
        
        public listarTutoresPorNombreResponse(InterfazDATMA.TutorWS.tutor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTutores", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarTodosTutoresRequest {
        
        public listarTodosTutoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTutoresResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarTodosTutoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.TutorWS.tutor[] @return;
        
        public listarTodosTutoresResponse() {
        }
        
        public listarTodosTutoresResponse(InterfazDATMA.TutorWS.tutor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarDNI", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class verificarDNIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apPat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apMat;
        
        public verificarDNIRequest() {
        }
        
        public verificarDNIRequest(string dni, string nom, string apPat, string apMat) {
            this.dni = dni;
            this.nom = nom;
            this.apPat = apPat;
            this.apMat = apMat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarDNIResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class verificarDNIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public verificarDNIResponse() {
        }
        
        public verificarDNIResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTutor", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarTutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.TutorWS.tutor tutor;
        
        public insertarTutorRequest() {
        }
        
        public insertarTutorRequest(InterfazDATMA.TutorWS.tutor tutor) {
            this.tutor = tutor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTutorResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarTutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTutorResponse() {
        }
        
        public insertarTutorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTutor", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarTutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.TutorWS.tutor tutor;
        
        public modificarTutorRequest() {
        }
        
        public modificarTutorRequest(InterfazDATMA.TutorWS.tutor tutor) {
            this.tutor = tutor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTutorResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarTutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTutorResponse() {
        }
        
        public modificarTutorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTutor", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarTutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTutor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public eliminarTutorRequest() {
        }
        
        public eliminarTutorRequest(int idTutor, int idUsuario) {
            this.idTutor = idTutor;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTutorResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarTutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTutorResponse() {
        }
        
        public eliminarTutorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TutorWSChannel : InterfazDATMA.TutorWS.TutorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TutorWSClient : System.ServiceModel.ClientBase<InterfazDATMA.TutorWS.TutorWS>, InterfazDATMA.TutorWS.TutorWS {
        
        public TutorWSClient() {
        }
        
        public TutorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TutorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TutorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TutorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.TutorWS.listarTutoresPorNombreResponse InterfazDATMA.TutorWS.TutorWS.listarTutoresPorNombre(InterfazDATMA.TutorWS.listarTutoresPorNombreRequest request) {
            return base.Channel.listarTutoresPorNombre(request);
        }
        
        public InterfazDATMA.TutorWS.tutor[] listarTutoresPorNombre(string nombreTutor) {
            InterfazDATMA.TutorWS.listarTutoresPorNombreRequest inValue = new InterfazDATMA.TutorWS.listarTutoresPorNombreRequest();
            inValue.nombreTutor = nombreTutor;
            InterfazDATMA.TutorWS.listarTutoresPorNombreResponse retVal = ((InterfazDATMA.TutorWS.TutorWS)(this)).listarTutoresPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.listarTutoresPorNombreResponse> InterfazDATMA.TutorWS.TutorWS.listarTutoresPorNombreAsync(InterfazDATMA.TutorWS.listarTutoresPorNombreRequest request) {
            return base.Channel.listarTutoresPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.TutorWS.listarTutoresPorNombreResponse> listarTutoresPorNombreAsync(string nombreTutor) {
            InterfazDATMA.TutorWS.listarTutoresPorNombreRequest inValue = new InterfazDATMA.TutorWS.listarTutoresPorNombreRequest();
            inValue.nombreTutor = nombreTutor;
            return ((InterfazDATMA.TutorWS.TutorWS)(this)).listarTutoresPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.TutorWS.listarTodosTutoresResponse InterfazDATMA.TutorWS.TutorWS.listarTodosTutores(InterfazDATMA.TutorWS.listarTodosTutoresRequest request) {
            return base.Channel.listarTodosTutores(request);
        }
        
        public InterfazDATMA.TutorWS.tutor[] listarTodosTutores() {
            InterfazDATMA.TutorWS.listarTodosTutoresRequest inValue = new InterfazDATMA.TutorWS.listarTodosTutoresRequest();
            InterfazDATMA.TutorWS.listarTodosTutoresResponse retVal = ((InterfazDATMA.TutorWS.TutorWS)(this)).listarTodosTutores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.listarTodosTutoresResponse> InterfazDATMA.TutorWS.TutorWS.listarTodosTutoresAsync(InterfazDATMA.TutorWS.listarTodosTutoresRequest request) {
            return base.Channel.listarTodosTutoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.TutorWS.listarTodosTutoresResponse> listarTodosTutoresAsync() {
            InterfazDATMA.TutorWS.listarTodosTutoresRequest inValue = new InterfazDATMA.TutorWS.listarTodosTutoresRequest();
            return ((InterfazDATMA.TutorWS.TutorWS)(this)).listarTodosTutoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.TutorWS.verificarDNIResponse InterfazDATMA.TutorWS.TutorWS.verificarDNI(InterfazDATMA.TutorWS.verificarDNIRequest request) {
            return base.Channel.verificarDNI(request);
        }
        
        public int verificarDNI(string dni, string nom, string apPat, string apMat) {
            InterfazDATMA.TutorWS.verificarDNIRequest inValue = new InterfazDATMA.TutorWS.verificarDNIRequest();
            inValue.dni = dni;
            inValue.nom = nom;
            inValue.apPat = apPat;
            inValue.apMat = apMat;
            InterfazDATMA.TutorWS.verificarDNIResponse retVal = ((InterfazDATMA.TutorWS.TutorWS)(this)).verificarDNI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.verificarDNIResponse> InterfazDATMA.TutorWS.TutorWS.verificarDNIAsync(InterfazDATMA.TutorWS.verificarDNIRequest request) {
            return base.Channel.verificarDNIAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.TutorWS.verificarDNIResponse> verificarDNIAsync(string dni, string nom, string apPat, string apMat) {
            InterfazDATMA.TutorWS.verificarDNIRequest inValue = new InterfazDATMA.TutorWS.verificarDNIRequest();
            inValue.dni = dni;
            inValue.nom = nom;
            inValue.apPat = apPat;
            inValue.apMat = apMat;
            return ((InterfazDATMA.TutorWS.TutorWS)(this)).verificarDNIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.TutorWS.insertarTutorResponse InterfazDATMA.TutorWS.TutorWS.insertarTutor(InterfazDATMA.TutorWS.insertarTutorRequest request) {
            return base.Channel.insertarTutor(request);
        }
        
        public int insertarTutor(InterfazDATMA.TutorWS.tutor tutor) {
            InterfazDATMA.TutorWS.insertarTutorRequest inValue = new InterfazDATMA.TutorWS.insertarTutorRequest();
            inValue.tutor = tutor;
            InterfazDATMA.TutorWS.insertarTutorResponse retVal = ((InterfazDATMA.TutorWS.TutorWS)(this)).insertarTutor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.insertarTutorResponse> InterfazDATMA.TutorWS.TutorWS.insertarTutorAsync(InterfazDATMA.TutorWS.insertarTutorRequest request) {
            return base.Channel.insertarTutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.TutorWS.insertarTutorResponse> insertarTutorAsync(InterfazDATMA.TutorWS.tutor tutor) {
            InterfazDATMA.TutorWS.insertarTutorRequest inValue = new InterfazDATMA.TutorWS.insertarTutorRequest();
            inValue.tutor = tutor;
            return ((InterfazDATMA.TutorWS.TutorWS)(this)).insertarTutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.TutorWS.modificarTutorResponse InterfazDATMA.TutorWS.TutorWS.modificarTutor(InterfazDATMA.TutorWS.modificarTutorRequest request) {
            return base.Channel.modificarTutor(request);
        }
        
        public int modificarTutor(InterfazDATMA.TutorWS.tutor tutor) {
            InterfazDATMA.TutorWS.modificarTutorRequest inValue = new InterfazDATMA.TutorWS.modificarTutorRequest();
            inValue.tutor = tutor;
            InterfazDATMA.TutorWS.modificarTutorResponse retVal = ((InterfazDATMA.TutorWS.TutorWS)(this)).modificarTutor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.modificarTutorResponse> InterfazDATMA.TutorWS.TutorWS.modificarTutorAsync(InterfazDATMA.TutorWS.modificarTutorRequest request) {
            return base.Channel.modificarTutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.TutorWS.modificarTutorResponse> modificarTutorAsync(InterfazDATMA.TutorWS.tutor tutor) {
            InterfazDATMA.TutorWS.modificarTutorRequest inValue = new InterfazDATMA.TutorWS.modificarTutorRequest();
            inValue.tutor = tutor;
            return ((InterfazDATMA.TutorWS.TutorWS)(this)).modificarTutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.TutorWS.eliminarTutorResponse InterfazDATMA.TutorWS.TutorWS.eliminarTutor(InterfazDATMA.TutorWS.eliminarTutorRequest request) {
            return base.Channel.eliminarTutor(request);
        }
        
        public int eliminarTutor(int idTutor, int idUsuario) {
            InterfazDATMA.TutorWS.eliminarTutorRequest inValue = new InterfazDATMA.TutorWS.eliminarTutorRequest();
            inValue.idTutor = idTutor;
            inValue.idUsuario = idUsuario;
            InterfazDATMA.TutorWS.eliminarTutorResponse retVal = ((InterfazDATMA.TutorWS.TutorWS)(this)).eliminarTutor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.TutorWS.eliminarTutorResponse> InterfazDATMA.TutorWS.TutorWS.eliminarTutorAsync(InterfazDATMA.TutorWS.eliminarTutorRequest request) {
            return base.Channel.eliminarTutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.TutorWS.eliminarTutorResponse> eliminarTutorAsync(int idTutor, int idUsuario) {
            InterfazDATMA.TutorWS.eliminarTutorRequest inValue = new InterfazDATMA.TutorWS.eliminarTutorRequest();
            inValue.idTutor = idTutor;
            inValue.idUsuario = idUsuario;
            return ((InterfazDATMA.TutorWS.TutorWS)(this)).eliminarTutorAsync(inValue);
        }
    }
}
