//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazDATMA.AsistenciaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.datmasoft.datma.pe/", ConfigurationName="AsistenciaWS.AsistenciaWS")]
    public interface AsistenciaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/AsistenciaWS/eliminarActividadRequest", ReplyAction="http://services.datmasoft.datma.pe/AsistenciaWS/eliminarActividadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.AsistenciaWS.eliminarActividadResponse eliminarActividad(InterfazDATMA.AsistenciaWS.eliminarActividadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/AsistenciaWS/eliminarActividadRequest", ReplyAction="http://services.datmasoft.datma.pe/AsistenciaWS/eliminarActividadResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.eliminarActividadResponse> eliminarActividadAsync(InterfazDATMA.AsistenciaWS.eliminarActividadRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/AsistenciaWS/modificarAsistenciaRequest", ReplyAction="http://services.datmasoft.datma.pe/AsistenciaWS/modificarAsistenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.AsistenciaWS.modificarAsistenciaResponse modificarAsistencia(InterfazDATMA.AsistenciaWS.modificarAsistenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/AsistenciaWS/modificarAsistenciaRequest", ReplyAction="http://services.datmasoft.datma.pe/AsistenciaWS/modificarAsistenciaResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.modificarAsistenciaResponse> modificarAsistenciaAsync(InterfazDATMA.AsistenciaWS.modificarAsistenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/AsistenciaWS/insertarAsistenciaRequest", ReplyAction="http://services.datmasoft.datma.pe/AsistenciaWS/insertarAsistenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.AsistenciaWS.insertarAsistenciaResponse insertarAsistencia(InterfazDATMA.AsistenciaWS.insertarAsistenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/AsistenciaWS/insertarAsistenciaRequest", ReplyAction="http://services.datmasoft.datma.pe/AsistenciaWS/insertarAsistenciaResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.insertarAsistenciaResponse> insertarAsistenciaAsync(InterfazDATMA.AsistenciaWS.insertarAsistenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/AsistenciaWS/listarAsistenciaRequest", ReplyAction="http://services.datmasoft.datma.pe/AsistenciaWS/listarAsistenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.AsistenciaWS.listarAsistenciaResponse listarAsistencia(InterfazDATMA.AsistenciaWS.listarAsistenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/AsistenciaWS/listarAsistenciaRequest", ReplyAction="http://services.datmasoft.datma.pe/AsistenciaWS/listarAsistenciaResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.listarAsistenciaResponse> listarAsistenciaAsync(InterfazDATMA.AsistenciaWS.listarAsistenciaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarActividad", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarActividadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAsistencia;
        
        public eliminarActividadRequest() {
        }
        
        public eliminarActividadRequest(int idAsistencia) {
            this.idAsistencia = idAsistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarActividadResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarActividadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarActividadResponse() {
        }
        
        public eliminarActividadResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class asistencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private actividad actividadField;
        
        private string descripcionField;
        
        private int idField;
        
        private int tipoField;
        
        private usuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public actividad actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
                this.RaisePropertyChanged("actividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class actividad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private localTime horaFinField;
        
        private localTime horaInicioField;
        
        private int idActividadField;
        
        private string linkZoomField;
        
        private material[] materialesField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localTime horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idActividad {
            get {
                return this.idActividadField;
            }
            set {
                this.idActividadField = value;
                this.RaisePropertyChanged("idActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string linkZoom {
            get {
                return this.linkZoomField;
            }
            set {
                this.linkZoomField = value;
                this.RaisePropertyChanged("linkZoom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("materiales", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public material[] materiales {
            get {
                return this.materialesField;
            }
            set {
                this.materialesField = value;
                this.RaisePropertyChanged("materiales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class localTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class distrito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idDistritoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idDistrito {
            get {
                return this.idDistritoField;
            }
            set {
                this.idDistritoField = value;
                this.RaisePropertyChanged("idDistrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string celularField;
        
        private string correoField;
        
        private string dNIField;
        
        private distrito distritoField;
        
        private int edadField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private ushort generoField;
        
        private int idPersonaField;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
                this.RaisePropertyChanged("DNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public distrito distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class usuario : persona {
        
        private int activoField;
        
        private byte[] fotoPerfilField;
        
        private int idUsuarioField;
        
        private string passwordField;
        
        private int tipoField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fotoPerfil {
            get {
                return this.fotoPerfilField;
            }
            set {
                this.fotoPerfilField = value;
                this.RaisePropertyChanged("fotoPerfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class material : object, System.ComponentModel.INotifyPropertyChanged {
        
        private actividad actividadField;
        
        private string descripcionField;
        
        private int estadoField;
        
        private int idMaterialField;
        
        private string nombreField;
        
        private int tipoMaterialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public actividad actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
                this.RaisePropertyChanged("actividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idMaterial {
            get {
                return this.idMaterialField;
            }
            set {
                this.idMaterialField = value;
                this.RaisePropertyChanged("idMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int tipoMaterial {
            get {
                return this.tipoMaterialField;
            }
            set {
                this.tipoMaterialField = value;
                this.RaisePropertyChanged("tipoMaterial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAsistencia", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarAsistenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.AsistenciaWS.asistencia asistencia;
        
        public modificarAsistenciaRequest() {
        }
        
        public modificarAsistenciaRequest(InterfazDATMA.AsistenciaWS.asistencia asistencia) {
            this.asistencia = asistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAsistenciaResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarAsistenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarAsistenciaResponse() {
        }
        
        public modificarAsistenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAsistencia", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarAsistenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.AsistenciaWS.asistencia asistencia;
        
        public insertarAsistenciaRequest() {
        }
        
        public insertarAsistenciaRequest(InterfazDATMA.AsistenciaWS.asistencia asistencia) {
            this.asistencia = asistencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAsistenciaResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarAsistenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAsistenciaResponse() {
        }
        
        public insertarAsistenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAsistencia", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarAsistenciaRequest {
        
        public listarAsistenciaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAsistenciaResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarAsistenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.AsistenciaWS.asistencia[] @return;
        
        public listarAsistenciaResponse() {
        }
        
        public listarAsistenciaResponse(InterfazDATMA.AsistenciaWS.asistencia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsistenciaWSChannel : InterfazDATMA.AsistenciaWS.AsistenciaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsistenciaWSClient : System.ServiceModel.ClientBase<InterfazDATMA.AsistenciaWS.AsistenciaWS>, InterfazDATMA.AsistenciaWS.AsistenciaWS {
        
        public AsistenciaWSClient() {
        }
        
        public AsistenciaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsistenciaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsistenciaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsistenciaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.AsistenciaWS.eliminarActividadResponse InterfazDATMA.AsistenciaWS.AsistenciaWS.eliminarActividad(InterfazDATMA.AsistenciaWS.eliminarActividadRequest request) {
            return base.Channel.eliminarActividad(request);
        }
        
        public int eliminarActividad(int idAsistencia) {
            InterfazDATMA.AsistenciaWS.eliminarActividadRequest inValue = new InterfazDATMA.AsistenciaWS.eliminarActividadRequest();
            inValue.idAsistencia = idAsistencia;
            InterfazDATMA.AsistenciaWS.eliminarActividadResponse retVal = ((InterfazDATMA.AsistenciaWS.AsistenciaWS)(this)).eliminarActividad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.eliminarActividadResponse> InterfazDATMA.AsistenciaWS.AsistenciaWS.eliminarActividadAsync(InterfazDATMA.AsistenciaWS.eliminarActividadRequest request) {
            return base.Channel.eliminarActividadAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.eliminarActividadResponse> eliminarActividadAsync(int idAsistencia) {
            InterfazDATMA.AsistenciaWS.eliminarActividadRequest inValue = new InterfazDATMA.AsistenciaWS.eliminarActividadRequest();
            inValue.idAsistencia = idAsistencia;
            return ((InterfazDATMA.AsistenciaWS.AsistenciaWS)(this)).eliminarActividadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.AsistenciaWS.modificarAsistenciaResponse InterfazDATMA.AsistenciaWS.AsistenciaWS.modificarAsistencia(InterfazDATMA.AsistenciaWS.modificarAsistenciaRequest request) {
            return base.Channel.modificarAsistencia(request);
        }
        
        public int modificarAsistencia(InterfazDATMA.AsistenciaWS.asistencia asistencia) {
            InterfazDATMA.AsistenciaWS.modificarAsistenciaRequest inValue = new InterfazDATMA.AsistenciaWS.modificarAsistenciaRequest();
            inValue.asistencia = asistencia;
            InterfazDATMA.AsistenciaWS.modificarAsistenciaResponse retVal = ((InterfazDATMA.AsistenciaWS.AsistenciaWS)(this)).modificarAsistencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.modificarAsistenciaResponse> InterfazDATMA.AsistenciaWS.AsistenciaWS.modificarAsistenciaAsync(InterfazDATMA.AsistenciaWS.modificarAsistenciaRequest request) {
            return base.Channel.modificarAsistenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.modificarAsistenciaResponse> modificarAsistenciaAsync(InterfazDATMA.AsistenciaWS.asistencia asistencia) {
            InterfazDATMA.AsistenciaWS.modificarAsistenciaRequest inValue = new InterfazDATMA.AsistenciaWS.modificarAsistenciaRequest();
            inValue.asistencia = asistencia;
            return ((InterfazDATMA.AsistenciaWS.AsistenciaWS)(this)).modificarAsistenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.AsistenciaWS.insertarAsistenciaResponse InterfazDATMA.AsistenciaWS.AsistenciaWS.insertarAsistencia(InterfazDATMA.AsistenciaWS.insertarAsistenciaRequest request) {
            return base.Channel.insertarAsistencia(request);
        }
        
        public int insertarAsistencia(InterfazDATMA.AsistenciaWS.asistencia asistencia) {
            InterfazDATMA.AsistenciaWS.insertarAsistenciaRequest inValue = new InterfazDATMA.AsistenciaWS.insertarAsistenciaRequest();
            inValue.asistencia = asistencia;
            InterfazDATMA.AsistenciaWS.insertarAsistenciaResponse retVal = ((InterfazDATMA.AsistenciaWS.AsistenciaWS)(this)).insertarAsistencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.insertarAsistenciaResponse> InterfazDATMA.AsistenciaWS.AsistenciaWS.insertarAsistenciaAsync(InterfazDATMA.AsistenciaWS.insertarAsistenciaRequest request) {
            return base.Channel.insertarAsistenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.insertarAsistenciaResponse> insertarAsistenciaAsync(InterfazDATMA.AsistenciaWS.asistencia asistencia) {
            InterfazDATMA.AsistenciaWS.insertarAsistenciaRequest inValue = new InterfazDATMA.AsistenciaWS.insertarAsistenciaRequest();
            inValue.asistencia = asistencia;
            return ((InterfazDATMA.AsistenciaWS.AsistenciaWS)(this)).insertarAsistenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.AsistenciaWS.listarAsistenciaResponse InterfazDATMA.AsistenciaWS.AsistenciaWS.listarAsistencia(InterfazDATMA.AsistenciaWS.listarAsistenciaRequest request) {
            return base.Channel.listarAsistencia(request);
        }
        
        public InterfazDATMA.AsistenciaWS.asistencia[] listarAsistencia() {
            InterfazDATMA.AsistenciaWS.listarAsistenciaRequest inValue = new InterfazDATMA.AsistenciaWS.listarAsistenciaRequest();
            InterfazDATMA.AsistenciaWS.listarAsistenciaResponse retVal = ((InterfazDATMA.AsistenciaWS.AsistenciaWS)(this)).listarAsistencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.listarAsistenciaResponse> InterfazDATMA.AsistenciaWS.AsistenciaWS.listarAsistenciaAsync(InterfazDATMA.AsistenciaWS.listarAsistenciaRequest request) {
            return base.Channel.listarAsistenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.AsistenciaWS.listarAsistenciaResponse> listarAsistenciaAsync() {
            InterfazDATMA.AsistenciaWS.listarAsistenciaRequest inValue = new InterfazDATMA.AsistenciaWS.listarAsistenciaRequest();
            return ((InterfazDATMA.AsistenciaWS.AsistenciaWS)(this)).listarAsistenciaAsync(inValue);
        }
    }
}
