//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazDATMA.TemaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.datmasoft.datma.pe/", ConfigurationName="TemaWS.TemaWS")]
    public interface TemaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TemaWS/insertarTemaRequest", ReplyAction="http://services.datmasoft.datma.pe/TemaWS/insertarTemaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.TemaWS.insertarTemaResponse insertarTema(InterfazDATMA.TemaWS.insertarTemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TemaWS/insertarTemaRequest", ReplyAction="http://services.datmasoft.datma.pe/TemaWS/insertarTemaResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.TemaWS.insertarTemaResponse> insertarTemaAsync(InterfazDATMA.TemaWS.insertarTemaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TemaWS/modificarTemaRequest", ReplyAction="http://services.datmasoft.datma.pe/TemaWS/modificarTemaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.TemaWS.modificarTemaResponse modificarTema(InterfazDATMA.TemaWS.modificarTemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TemaWS/modificarTemaRequest", ReplyAction="http://services.datmasoft.datma.pe/TemaWS/modificarTemaResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.TemaWS.modificarTemaResponse> modificarTemaAsync(InterfazDATMA.TemaWS.modificarTemaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TemaWS/listarTemasRequest", ReplyAction="http://services.datmasoft.datma.pe/TemaWS/listarTemasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.TemaWS.listarTemasResponse listarTemas(InterfazDATMA.TemaWS.listarTemasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/TemaWS/listarTemasRequest", ReplyAction="http://services.datmasoft.datma.pe/TemaWS/listarTemasResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.TemaWS.listarTemasResponse> listarTemasAsync(InterfazDATMA.TemaWS.listarTemasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class tema : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTema", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarTemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.TemaWS.tema tema;
        
        public insertarTemaRequest() {
        }
        
        public insertarTemaRequest(InterfazDATMA.TemaWS.tema tema) {
            this.tema = tema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTemaResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarTemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTemaResponse() {
        }
        
        public insertarTemaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTema", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarTemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.TemaWS.tema tema;
        
        public modificarTemaRequest() {
        }
        
        public modificarTemaRequest(InterfazDATMA.TemaWS.tema tema) {
            this.tema = tema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTemaResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarTemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTemaResponse() {
        }
        
        public modificarTemaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTemas", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarTemasRequest {
        
        public listarTemasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTemasResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarTemasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.TemaWS.tema[] @return;
        
        public listarTemasResponse() {
        }
        
        public listarTemasResponse(InterfazDATMA.TemaWS.tema[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TemaWSChannel : InterfazDATMA.TemaWS.TemaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TemaWSClient : System.ServiceModel.ClientBase<InterfazDATMA.TemaWS.TemaWS>, InterfazDATMA.TemaWS.TemaWS {
        
        public TemaWSClient() {
        }
        
        public TemaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.TemaWS.insertarTemaResponse InterfazDATMA.TemaWS.TemaWS.insertarTema(InterfazDATMA.TemaWS.insertarTemaRequest request) {
            return base.Channel.insertarTema(request);
        }
        
        public int insertarTema(InterfazDATMA.TemaWS.tema tema) {
            InterfazDATMA.TemaWS.insertarTemaRequest inValue = new InterfazDATMA.TemaWS.insertarTemaRequest();
            inValue.tema = tema;
            InterfazDATMA.TemaWS.insertarTemaResponse retVal = ((InterfazDATMA.TemaWS.TemaWS)(this)).insertarTema(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.TemaWS.insertarTemaResponse> InterfazDATMA.TemaWS.TemaWS.insertarTemaAsync(InterfazDATMA.TemaWS.insertarTemaRequest request) {
            return base.Channel.insertarTemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.TemaWS.insertarTemaResponse> insertarTemaAsync(InterfazDATMA.TemaWS.tema tema) {
            InterfazDATMA.TemaWS.insertarTemaRequest inValue = new InterfazDATMA.TemaWS.insertarTemaRequest();
            inValue.tema = tema;
            return ((InterfazDATMA.TemaWS.TemaWS)(this)).insertarTemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.TemaWS.modificarTemaResponse InterfazDATMA.TemaWS.TemaWS.modificarTema(InterfazDATMA.TemaWS.modificarTemaRequest request) {
            return base.Channel.modificarTema(request);
        }
        
        public int modificarTema(InterfazDATMA.TemaWS.tema tema) {
            InterfazDATMA.TemaWS.modificarTemaRequest inValue = new InterfazDATMA.TemaWS.modificarTemaRequest();
            inValue.tema = tema;
            InterfazDATMA.TemaWS.modificarTemaResponse retVal = ((InterfazDATMA.TemaWS.TemaWS)(this)).modificarTema(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.TemaWS.modificarTemaResponse> InterfazDATMA.TemaWS.TemaWS.modificarTemaAsync(InterfazDATMA.TemaWS.modificarTemaRequest request) {
            return base.Channel.modificarTemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.TemaWS.modificarTemaResponse> modificarTemaAsync(InterfazDATMA.TemaWS.tema tema) {
            InterfazDATMA.TemaWS.modificarTemaRequest inValue = new InterfazDATMA.TemaWS.modificarTemaRequest();
            inValue.tema = tema;
            return ((InterfazDATMA.TemaWS.TemaWS)(this)).modificarTemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.TemaWS.listarTemasResponse InterfazDATMA.TemaWS.TemaWS.listarTemas(InterfazDATMA.TemaWS.listarTemasRequest request) {
            return base.Channel.listarTemas(request);
        }
        
        public InterfazDATMA.TemaWS.tema[] listarTemas() {
            InterfazDATMA.TemaWS.listarTemasRequest inValue = new InterfazDATMA.TemaWS.listarTemasRequest();
            InterfazDATMA.TemaWS.listarTemasResponse retVal = ((InterfazDATMA.TemaWS.TemaWS)(this)).listarTemas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.TemaWS.listarTemasResponse> InterfazDATMA.TemaWS.TemaWS.listarTemasAsync(InterfazDATMA.TemaWS.listarTemasRequest request) {
            return base.Channel.listarTemasAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.TemaWS.listarTemasResponse> listarTemasAsync() {
            InterfazDATMA.TemaWS.listarTemasRequest inValue = new InterfazDATMA.TemaWS.listarTemasRequest();
            return ((InterfazDATMA.TemaWS.TemaWS)(this)).listarTemasAsync(inValue);
        }
    }
}
