//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazDATMA.MaterialWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.datmasoft.datma.pe/", ConfigurationName="MaterialWS.MaterialWS")]
    public interface MaterialWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/modificarMaterialDocumentoRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/modificarMaterialDocumentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.MaterialWS.modificarMaterialDocumentoResponse modificarMaterialDocumento(InterfazDATMA.MaterialWS.modificarMaterialDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/modificarMaterialDocumentoRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/modificarMaterialDocumentoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.modificarMaterialDocumentoResponse> modificarMaterialDocumentoAsync(InterfazDATMA.MaterialWS.modificarMaterialDocumentoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/insertarMaterialDocumentoRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/insertarMaterialDocumentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.MaterialWS.insertarMaterialDocumentoResponse insertarMaterialDocumento(InterfazDATMA.MaterialWS.insertarMaterialDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/insertarMaterialDocumentoRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/insertarMaterialDocumentoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.insertarMaterialDocumentoResponse> insertarMaterialDocumentoAsync(InterfazDATMA.MaterialWS.insertarMaterialDocumentoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/insertarMaterialVideoRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/insertarMaterialVideoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.MaterialWS.insertarMaterialVideoResponse insertarMaterialVideo(InterfazDATMA.MaterialWS.insertarMaterialVideoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/insertarMaterialVideoRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/insertarMaterialVideoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.insertarMaterialVideoResponse> insertarMaterialVideoAsync(InterfazDATMA.MaterialWS.insertarMaterialVideoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/modificarMaterialVideoRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/modificarMaterialVideoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.MaterialWS.modificarMaterialVideoResponse modificarMaterialVideo(InterfazDATMA.MaterialWS.modificarMaterialVideoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/modificarMaterialVideoRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/modificarMaterialVideoResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.modificarMaterialVideoResponse> modificarMaterialVideoAsync(InterfazDATMA.MaterialWS.modificarMaterialVideoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/listarDocumentosRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/listarDocumentosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.MaterialWS.listarDocumentosResponse listarDocumentos(InterfazDATMA.MaterialWS.listarDocumentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/listarDocumentosRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/listarDocumentosResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.listarDocumentosResponse> listarDocumentosAsync(InterfazDATMA.MaterialWS.listarDocumentosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/eliminarMaterialRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/eliminarMaterialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.MaterialWS.eliminarMaterialResponse eliminarMaterial(InterfazDATMA.MaterialWS.eliminarMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/eliminarMaterialRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/eliminarMaterialResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.eliminarMaterialResponse> eliminarMaterialAsync(InterfazDATMA.MaterialWS.eliminarMaterialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/listarVideosRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/listarVideosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        InterfazDATMA.MaterialWS.listarVideosResponse listarVideos(InterfazDATMA.MaterialWS.listarVideosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.datmasoft.datma.pe/MaterialWS/listarVideosRequest", ReplyAction="http://services.datmasoft.datma.pe/MaterialWS/listarVideosResponse")]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.listarVideosResponse> listarVideosAsync(InterfazDATMA.MaterialWS.listarVideosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class documento : material {
        
        private byte[] docPDFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] docPDF {
            get {
                return this.docPDFField;
            }
            set {
                this.docPDFField = value;
                this.RaisePropertyChanged("docPDF");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(video))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class material : object, System.ComponentModel.INotifyPropertyChanged {
        
        private actividad actividadField;
        
        private string descripcionField;
        
        private int estadoField;
        
        private int idMaterialField;
        
        private string nombreField;
        
        private int tipoMaterialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public actividad actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
                this.RaisePropertyChanged("actividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idMaterial {
            get {
                return this.idMaterialField;
            }
            set {
                this.idMaterialField = value;
                this.RaisePropertyChanged("idMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int tipoMaterial {
            get {
                return this.tipoMaterialField;
            }
            set {
                this.tipoMaterialField = value;
                this.RaisePropertyChanged("tipoMaterial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class actividad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private localTime horaFinField;
        
        private localTime horaInicioField;
        
        private int idActividadField;
        
        private string linkZoomField;
        
        private material[] materialesField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localTime horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idActividad {
            get {
                return this.idActividadField;
            }
            set {
                this.idActividadField = value;
                this.RaisePropertyChanged("idActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string linkZoom {
            get {
                return this.linkZoomField;
            }
            set {
                this.linkZoomField = value;
                this.RaisePropertyChanged("linkZoom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("materiales", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public material[] materiales {
            get {
                return this.materialesField;
            }
            set {
                this.materialesField = value;
                this.RaisePropertyChanged("materiales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class localTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.datmasoft.datma.pe/")]
    public partial class video : material {
        
        private string duracionField;
        
        private string linkVideoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string linkVideo {
            get {
                return this.linkVideoField;
            }
            set {
                this.linkVideoField = value;
                this.RaisePropertyChanged("linkVideo");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMaterialDocumento", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarMaterialDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.MaterialWS.documento doc;
        
        public modificarMaterialDocumentoRequest() {
        }
        
        public modificarMaterialDocumentoRequest(InterfazDATMA.MaterialWS.documento doc) {
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMaterialDocumentoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarMaterialDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarMaterialDocumentoResponse() {
        }
        
        public modificarMaterialDocumentoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMaterialDocumento", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarMaterialDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.MaterialWS.documento doc;
        
        public insertarMaterialDocumentoRequest() {
        }
        
        public insertarMaterialDocumentoRequest(InterfazDATMA.MaterialWS.documento doc) {
            this.doc = doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMaterialDocumentoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarMaterialDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarMaterialDocumentoResponse() {
        }
        
        public insertarMaterialDocumentoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMaterialVideo", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarMaterialVideoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.MaterialWS.video video;
        
        public insertarMaterialVideoRequest() {
        }
        
        public insertarMaterialVideoRequest(InterfazDATMA.MaterialWS.video video) {
            this.video = video;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarMaterialVideoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class insertarMaterialVideoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarMaterialVideoResponse() {
        }
        
        public insertarMaterialVideoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMaterialVideo", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarMaterialVideoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.MaterialWS.video video;
        
        public modificarMaterialVideoRequest() {
        }
        
        public modificarMaterialVideoRequest(InterfazDATMA.MaterialWS.video video) {
            this.video = video;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarMaterialVideoResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class modificarMaterialVideoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarMaterialVideoResponse() {
        }
        
        public modificarMaterialVideoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDocumentos", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarDocumentosRequest {
        
        public listarDocumentosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDocumentosResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarDocumentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.MaterialWS.documento[] @return;
        
        public listarDocumentosResponse() {
        }
        
        public listarDocumentosResponse(InterfazDATMA.MaterialWS.documento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMaterial", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMat;
        
        public eliminarMaterialRequest() {
        }
        
        public eliminarMaterialRequest(int idMat) {
            this.idMat = idMat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarMaterialResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class eliminarMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarMaterialResponse() {
        }
        
        public eliminarMaterialResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVideos", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarVideosRequest {
        
        public listarVideosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVideosResponse", WrapperNamespace="http://services.datmasoft.datma.pe/", IsWrapped=true)]
    public partial class listarVideosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.datmasoft.datma.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfazDATMA.MaterialWS.video[] @return;
        
        public listarVideosResponse() {
        }
        
        public listarVideosResponse(InterfazDATMA.MaterialWS.video[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaterialWSChannel : InterfazDATMA.MaterialWS.MaterialWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialWSClient : System.ServiceModel.ClientBase<InterfazDATMA.MaterialWS.MaterialWS>, InterfazDATMA.MaterialWS.MaterialWS {
        
        public MaterialWSClient() {
        }
        
        public MaterialWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.MaterialWS.modificarMaterialDocumentoResponse InterfazDATMA.MaterialWS.MaterialWS.modificarMaterialDocumento(InterfazDATMA.MaterialWS.modificarMaterialDocumentoRequest request) {
            return base.Channel.modificarMaterialDocumento(request);
        }
        
        public int modificarMaterialDocumento(InterfazDATMA.MaterialWS.documento doc) {
            InterfazDATMA.MaterialWS.modificarMaterialDocumentoRequest inValue = new InterfazDATMA.MaterialWS.modificarMaterialDocumentoRequest();
            inValue.doc = doc;
            InterfazDATMA.MaterialWS.modificarMaterialDocumentoResponse retVal = ((InterfazDATMA.MaterialWS.MaterialWS)(this)).modificarMaterialDocumento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.modificarMaterialDocumentoResponse> InterfazDATMA.MaterialWS.MaterialWS.modificarMaterialDocumentoAsync(InterfazDATMA.MaterialWS.modificarMaterialDocumentoRequest request) {
            return base.Channel.modificarMaterialDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.modificarMaterialDocumentoResponse> modificarMaterialDocumentoAsync(InterfazDATMA.MaterialWS.documento doc) {
            InterfazDATMA.MaterialWS.modificarMaterialDocumentoRequest inValue = new InterfazDATMA.MaterialWS.modificarMaterialDocumentoRequest();
            inValue.doc = doc;
            return ((InterfazDATMA.MaterialWS.MaterialWS)(this)).modificarMaterialDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.MaterialWS.insertarMaterialDocumentoResponse InterfazDATMA.MaterialWS.MaterialWS.insertarMaterialDocumento(InterfazDATMA.MaterialWS.insertarMaterialDocumentoRequest request) {
            return base.Channel.insertarMaterialDocumento(request);
        }
        
        public int insertarMaterialDocumento(InterfazDATMA.MaterialWS.documento doc) {
            InterfazDATMA.MaterialWS.insertarMaterialDocumentoRequest inValue = new InterfazDATMA.MaterialWS.insertarMaterialDocumentoRequest();
            inValue.doc = doc;
            InterfazDATMA.MaterialWS.insertarMaterialDocumentoResponse retVal = ((InterfazDATMA.MaterialWS.MaterialWS)(this)).insertarMaterialDocumento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.insertarMaterialDocumentoResponse> InterfazDATMA.MaterialWS.MaterialWS.insertarMaterialDocumentoAsync(InterfazDATMA.MaterialWS.insertarMaterialDocumentoRequest request) {
            return base.Channel.insertarMaterialDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.insertarMaterialDocumentoResponse> insertarMaterialDocumentoAsync(InterfazDATMA.MaterialWS.documento doc) {
            InterfazDATMA.MaterialWS.insertarMaterialDocumentoRequest inValue = new InterfazDATMA.MaterialWS.insertarMaterialDocumentoRequest();
            inValue.doc = doc;
            return ((InterfazDATMA.MaterialWS.MaterialWS)(this)).insertarMaterialDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.MaterialWS.insertarMaterialVideoResponse InterfazDATMA.MaterialWS.MaterialWS.insertarMaterialVideo(InterfazDATMA.MaterialWS.insertarMaterialVideoRequest request) {
            return base.Channel.insertarMaterialVideo(request);
        }
        
        public int insertarMaterialVideo(InterfazDATMA.MaterialWS.video video) {
            InterfazDATMA.MaterialWS.insertarMaterialVideoRequest inValue = new InterfazDATMA.MaterialWS.insertarMaterialVideoRequest();
            inValue.video = video;
            InterfazDATMA.MaterialWS.insertarMaterialVideoResponse retVal = ((InterfazDATMA.MaterialWS.MaterialWS)(this)).insertarMaterialVideo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.insertarMaterialVideoResponse> InterfazDATMA.MaterialWS.MaterialWS.insertarMaterialVideoAsync(InterfazDATMA.MaterialWS.insertarMaterialVideoRequest request) {
            return base.Channel.insertarMaterialVideoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.insertarMaterialVideoResponse> insertarMaterialVideoAsync(InterfazDATMA.MaterialWS.video video) {
            InterfazDATMA.MaterialWS.insertarMaterialVideoRequest inValue = new InterfazDATMA.MaterialWS.insertarMaterialVideoRequest();
            inValue.video = video;
            return ((InterfazDATMA.MaterialWS.MaterialWS)(this)).insertarMaterialVideoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.MaterialWS.modificarMaterialVideoResponse InterfazDATMA.MaterialWS.MaterialWS.modificarMaterialVideo(InterfazDATMA.MaterialWS.modificarMaterialVideoRequest request) {
            return base.Channel.modificarMaterialVideo(request);
        }
        
        public int modificarMaterialVideo(InterfazDATMA.MaterialWS.video video) {
            InterfazDATMA.MaterialWS.modificarMaterialVideoRequest inValue = new InterfazDATMA.MaterialWS.modificarMaterialVideoRequest();
            inValue.video = video;
            InterfazDATMA.MaterialWS.modificarMaterialVideoResponse retVal = ((InterfazDATMA.MaterialWS.MaterialWS)(this)).modificarMaterialVideo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.modificarMaterialVideoResponse> InterfazDATMA.MaterialWS.MaterialWS.modificarMaterialVideoAsync(InterfazDATMA.MaterialWS.modificarMaterialVideoRequest request) {
            return base.Channel.modificarMaterialVideoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.modificarMaterialVideoResponse> modificarMaterialVideoAsync(InterfazDATMA.MaterialWS.video video) {
            InterfazDATMA.MaterialWS.modificarMaterialVideoRequest inValue = new InterfazDATMA.MaterialWS.modificarMaterialVideoRequest();
            inValue.video = video;
            return ((InterfazDATMA.MaterialWS.MaterialWS)(this)).modificarMaterialVideoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.MaterialWS.listarDocumentosResponse InterfazDATMA.MaterialWS.MaterialWS.listarDocumentos(InterfazDATMA.MaterialWS.listarDocumentosRequest request) {
            return base.Channel.listarDocumentos(request);
        }
        
        public InterfazDATMA.MaterialWS.documento[] listarDocumentos() {
            InterfazDATMA.MaterialWS.listarDocumentosRequest inValue = new InterfazDATMA.MaterialWS.listarDocumentosRequest();
            InterfazDATMA.MaterialWS.listarDocumentosResponse retVal = ((InterfazDATMA.MaterialWS.MaterialWS)(this)).listarDocumentos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.listarDocumentosResponse> InterfazDATMA.MaterialWS.MaterialWS.listarDocumentosAsync(InterfazDATMA.MaterialWS.listarDocumentosRequest request) {
            return base.Channel.listarDocumentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.listarDocumentosResponse> listarDocumentosAsync() {
            InterfazDATMA.MaterialWS.listarDocumentosRequest inValue = new InterfazDATMA.MaterialWS.listarDocumentosRequest();
            return ((InterfazDATMA.MaterialWS.MaterialWS)(this)).listarDocumentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.MaterialWS.eliminarMaterialResponse InterfazDATMA.MaterialWS.MaterialWS.eliminarMaterial(InterfazDATMA.MaterialWS.eliminarMaterialRequest request) {
            return base.Channel.eliminarMaterial(request);
        }
        
        public int eliminarMaterial(int idMat) {
            InterfazDATMA.MaterialWS.eliminarMaterialRequest inValue = new InterfazDATMA.MaterialWS.eliminarMaterialRequest();
            inValue.idMat = idMat;
            InterfazDATMA.MaterialWS.eliminarMaterialResponse retVal = ((InterfazDATMA.MaterialWS.MaterialWS)(this)).eliminarMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.eliminarMaterialResponse> InterfazDATMA.MaterialWS.MaterialWS.eliminarMaterialAsync(InterfazDATMA.MaterialWS.eliminarMaterialRequest request) {
            return base.Channel.eliminarMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.eliminarMaterialResponse> eliminarMaterialAsync(int idMat) {
            InterfazDATMA.MaterialWS.eliminarMaterialRequest inValue = new InterfazDATMA.MaterialWS.eliminarMaterialRequest();
            inValue.idMat = idMat;
            return ((InterfazDATMA.MaterialWS.MaterialWS)(this)).eliminarMaterialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InterfazDATMA.MaterialWS.listarVideosResponse InterfazDATMA.MaterialWS.MaterialWS.listarVideos(InterfazDATMA.MaterialWS.listarVideosRequest request) {
            return base.Channel.listarVideos(request);
        }
        
        public InterfazDATMA.MaterialWS.video[] listarVideos() {
            InterfazDATMA.MaterialWS.listarVideosRequest inValue = new InterfazDATMA.MaterialWS.listarVideosRequest();
            InterfazDATMA.MaterialWS.listarVideosResponse retVal = ((InterfazDATMA.MaterialWS.MaterialWS)(this)).listarVideos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.listarVideosResponse> InterfazDATMA.MaterialWS.MaterialWS.listarVideosAsync(InterfazDATMA.MaterialWS.listarVideosRequest request) {
            return base.Channel.listarVideosAsync(request);
        }
        
        public System.Threading.Tasks.Task<InterfazDATMA.MaterialWS.listarVideosResponse> listarVideosAsync() {
            InterfazDATMA.MaterialWS.listarVideosRequest inValue = new InterfazDATMA.MaterialWS.listarVideosRequest();
            return ((InterfazDATMA.MaterialWS.MaterialWS)(this)).listarVideosAsync(inValue);
        }
    }
}
